modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL="https://github.com/Ocelot5836/Server-Mod-Downloader/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"
updateJSONURL="https://raw.githubusercontent.com/Ocelot5836/storage/master/mods/serverdownloader/update.json"
displayURL="https://github.com/Ocelot5836/Server-Mod-Downloader"

[modproperties.${mod_id}]
catalogueItemIcon="minecraft:gold_block"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"